Repository hashicorp/aws-sdk-go-base, pull requests merged in 2020-06, with the labels that each got.

#28 Enable additional golangci-lint linters and fix reports
  .golangci.yml
  awsauth.go
  awsauth_test.go
  awserr_test.go
  mock.go
  session.go
  session_test.go
  validation_test.go
Labels: tests

#32 Introduce more exhaustive GetSession testing and resolve some endpoint customization bugs
  awsauth.go
  awsauth_test.go
  awserr.go
  awserr_test.go
  endpoints.go
  mock.go
  session.go
  session_test.go
Labels: bug

#20 Feature/fix cred chain
  awsauth.go
  session.go
Labels: bug

#31 Update messaging, it is used in the backend also
  awsauth.go
  session_test.go
Labels: bug

#38 Always enable AWS shared configuration file support
  awsauth.go
  session.go
  session_test.go
Labels: enhancement

#40 Automatically handle shared credentials filename home directory expansion
  awsauth.go
  go.mod
  go.sum
Labels: enhancement

#39 Implement configuration assume role duration, policy ARNs, tags, and transitive tag keys
  awsauth.go
  config.go
  go.mod
  go.sum
  mock.go
Labels: enhancement

#41 Mock and verify Web Identity Token support (STS AssumeRoleWithWebIdentity)
  mock.go
  session_test.go
Labels: tests

#42 Introduce Go 1.13 compatible error types
  awsauth.go
  awsauth_test.go
  config.go
  errors.go
  session.go
  session_test.go
Labels: enhancement

#44 Fix SkipMetadataApiCheck and remove now extraneous GetCredentialsFromMetadata
  awsauth.go
  session.go
  session_test.go
Labels: bug
